# Tests the following:
# - docker image is built and runs.
# - docker image doesn't cause the app_code to build on the host workstation,
#   (but does build the app_code within the docker image multi-stage build).

.PHONY: test
test:
	./test.sh

